### ISSUE TITLE
Missing jar file

### ISSUE THREAD

**Issue by sandipshinde** [dnanhkhoa/CVParser#1]
I was looking into this project but was not able to locate the jar file to follow your instructions. 

cd cvparser/release
java -jar cvparser.jar <resume file> <output file>

It will be great if you can share the jar file as well. 

Regards,
Sandip

**Comment by sandipshinde** [comment]
Fixed it my own. Thanks.

**Comment by dnanhkhoa** [comment]
Hi @sandipshinde,

I didn't put that file into the release folder due to large size. But it's great if you could recompile by yourself. Thank you.

**Comment by sandipshinde** [comment]
Thanks, @dnanhkhoa I did recompile and worked great..!! Thanks..
